### ISSUE TITLE
Please add better sorting options for new feeds

### ISSUE THREAD

**Issue by lonseidman** [FreshRSS/Extensions#161] opened 2023-07-15 12:31 UTC
I realize this issue will be closed as soon as I open it, but I think it's worth putting this back on the front burner even for a short time. 

I am a new FreshRSS user. I've spent the better part of this week playing with all of the options out there for self-hosted RSS feeds and FreshRSS is the one I keep coming back to. While I subscribe to Bazqux for my day-to-day feed reading I wanted something I could use to consolidate my YouTube subscriptions into a topic-based system where I and not the YouTube algorithm decide what gets put in front of me. 

The problem I'm having is the same one that's been raised by many others: adding a new feed to the mix brings all of the articles from that feed to the top of the list regardless of the date they were posted. It seems as though this is by design but this is not a good user experience and not what any of the alternative readers are doing with new feeds. 

I have, with mixed success, used some MySQL code to reorder the database but it's a pain to have to do that every time I add a new group of feeds. And my code is not always able to do this reliably. 

It would be great to give the user the choice about how to sort new feeds into the database. Some may like this behavior but I think there's an equal number who don't.

**Comment by Alkarex** [comment] 2023-07-16 12:52
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/2596#issuecomment-1541934281 , which is on the roadmap

**Closed by Alkarex** 2023-07-16 12:52 UTC

**Comment by Alkarex** [comment] 2024-12-27 16:20
https://github.com/FreshRSS/FreshRSS/pull/7149
