### ISSUE TITLE
Reading time extension error

### ISSUE THREAD

**Issue by svemoe** [FreshRSS/Extensions#148] opened 2022-12-23 16:39 UTC
Reading time extension is not working for me.
In firefox console I get the error message `Uncaught TypeError: document.querySelector(...).childNodes[0].childNodes[2] is undefined`.
Maybe something in FreshRSS layout changed?
Anyone else have this problem?
When I switch to mobile view it's fine.

**Comment by Frenzie** [comment] 2022-12-23 19:23
At a quick glance I think that'll work as intended if you use ` document.querySelector("#" + reading_time.flux.id + " ul.horizontal-list li.item.website span") ` but I'm not 100% sure what it used to look like.

**Comment by math-GH** [comment] 2022-12-25 14:22
@svemoe Which FreshRSS version do you use? 1.20.2?

ping @lapineige as author of this extension.

**Comment by lapineige** [comment] 2022-12-25 14:39
It doesn't work for me on 1.20 indeed… I recently updated, I had no time to fix it.
I will try to take a look in the coming days, @svemoe don't hesitate to ping me if nothing happened in let's say 2 weeks :)

**Comment by Alkarex** [comment] 2023-03-09 11:18
Ping @lapineige ;-)

**Comment by lapineige** [comment] 2023-05-11 07:20
Fixed by #156 ?

**Closed** 2023-05-11 07:25 UTC
Labels: bug
