### ISSUE TITLE
[xExtension-ReadingTime] doesn't work unless "Date of publication" is checked

### ISSUE THREAD

**Issue by scripcat** [FreshRSS/Extensions#58] opened 2019-09-15 00:28 UTC
The time doesn't display at all (to the left of the article title) when "Date of publication" is not checked in the Display settings for the Article icons for the top line.

**Comment by Alkarex** [comment] 2019-09-28 21:20
@lapineige

**Comment by lapineige** [comment] 2019-09-29 08:45
@Alkarex is there a way for me to check if that option is disabled ?

**Comment by Alkarex** [comment] 2019-09-29 09:13
@lapineige You can test if your current article has the date information, e.g.

```javascript
article.querySelector('.flux_header > .date');
```

**Comment by lapineige** [comment] 2019-10-20 12:20
@scripcat I can't reproduce your error…

What's your configuration for the article header ? Default one, minus the date ?

What version of the extension are your using ? (the one from this official repository ?)

**Comment by lapineige** [comment] 2019-10-20 12:31
Did you also disable the arrow icon to link to the original article ?

If I disable both article date and this arrow icon (hence there is nothing in the right of the article title), then it fails.

**Comment by lapineige** [comment] 2019-10-20 13:07
I just pushed a fix.
Please test it, in my case it solves the issue.

**Closed** 2020-01-20 10:16 UTC
