### ISSUE TITLE
If there is an error in the extension.php for one ext there are no extensions available

### ISSUE THREAD

**Issue by dhoko** [FreshRSS/Extensions#2] opened 2015-01-25 18:50 UTC
Hello,

I'm trying to write a REST API for Fresh RSS.
There is a bug when you try to install a new extension, There was an I before Extension in the ClassName PHP, then there were no extensions available in Fresh. 

``` php
class FreshRSS_REST_IExtension extends Minz_Extension {
```

Log:

```
2015-01-25 19:46:46
`FreshRSS_RESTExtension` cannot be found in `/home/dhoko/dev/rss/FreshRSS-beta/extensions/xExtension-FreshRSS_REST/extension.php`
```

**Comment by marienfressinaud** [comment] 2015-01-26 10:30
It's not really a bug since FRSS didn't find what you declare to load in the metadata file. Anyway, it may be annoying especially for developers who can't understand the problem. I will see if I can improve that.

**Comment by dhoko** [comment] 2015-01-26 12:35
Hum it is, because I had 4 extensions, mine and these three. So ok it didn't find mine, but why did the list was empty ?

**Comment by marienfressinaud** [comment] 2015-01-26 13:35
Oh I didn't understand. That's not the intended behaviour indeed. Problem is I cannot reproduce your bug. Is it possible to send me an extension which break the extension list?

**Comment by dhoko** [comment] 2015-01-26 14:55
[Ext](https://github.com/dhoko/FreshRssApi)

To find the bug:

1. Use the last build on master
2. empty extension directory
3. clone this extension (*I fixed the name, so you have to change it*)
4. try to install it in the fresh admin
5. Clone these extensions
6. try to install

> I think you can clone my ext and yours at the same time

**Comment by marienfressinaud** [comment] 2015-01-26 15:38
Extension system has not been included in the master branch, I guess you meant beta?

**Comment by kevinpapst** [comment] 2017-12-21 21:59
@dhoko Is this still a problem for you? As this ticket is more than 2,5 years old I think its time to close it. If somebody encounters the problem again and tells us how to reproduce it, we can still fix it in a new ticket.

**Closed** 2017-12-21 22:21 UTC
